/**
 * Sprite baker, node half.
 *
 * Walks the curated catalogue, drives a headless Chromium through
 * page/renderer.mjs once per model per yaw, and writes the packed atlas
 * pages plus a generated manifest module.
 *
 *   node packages/tools/src/bake/bake.mjs [--page 4096] [--only <regex>]
 *
 * Inputs come from assets-src/raw, which is gitignored - run
 * packages/tools/src/bake/fetch-kits.mjs first if it is not there.
 */

import { createServer } from 'node:http';
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { KITS, RULES, LEAF_KITS } from './catalog.mjs';

const ROOT = resolve(fileURLToPath(new URL('../../../..', import.meta.url)));
const RAW = join(ROOT, 'assets-src', 'raw');
const OUT_IMG = join(ROOT, 'packages', 'game', 'public', 'atlas');
const OUT_MANIFEST = join(ROOT, 'packages', 'game', 'src', 'art', 'atlas.generated.ts');

const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = args.indexOf('--' + name);
  return i >= 0 ? args[i + 1] : fallback;
};
const PAGE_SIZE = Number(flag('page', 4096));
const ONLY = flag('only', null) ? new RegExp(flag('only')) : null;

const MIME = {
  '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript',
  '.json': 'application/json', '.glb': 'model/gltf-binary', '.png': 'image/png',
  '.jpg': 'image/jpeg', '.bin': 'application/octet-stream', '.map': 'application/json',
};

/**
 * Static server over the repo root.
 *
 * The page needs three trees that do not share a parent under any single
 * package: node_modules for three, packages for the renderer, assets-src for
 * the models. Serving the repo root is the one arrangement that reaches all
 * three without copying anything.
 */
function serve() {
  const server = createServer(async (req, res) => {
    try {
      const path = decodeURIComponent(new URL(req.url, 'http://x').pathname);
      // Refuse anything that climbs out of the repo.
      const file = resolve(join(ROOT, path));
      if (!file.startsWith(ROOT)) {
        res.writeHead(403).end('no');
        return;
      }
      const body = await readFile(file);
      res.writeHead(200, {
        'content-type': MIME[extname(file).toLowerCase()] ?? 'application/octet-stream',
        'cache-control': 'no-store',
      }).end(body);
    } catch {
      res.writeHead(404).end('missing');
    }
  });
  return new Promise((ok) => {
    server.listen(0, '127.0.0.1', () => ok({ server, port: server.address().port }));
  });
}

/** Expand the catalogue rules against what is actually on disk. */
async function planJobs() {
  const jobs = [];
  const seen = new Set();

  for (const [kitId, kit] of Object.entries(KITS)) {
    const dir = join(RAW, kit.dir, kit.glb);
    if (!existsSync(dir)) {
      console.warn('missing kit, skipping: ' + dir);
      continue;
    }
    const files = (await readdir(dir)).filter((f) => f.endsWith('.glb'));
    const rules = RULES.filter((r) => r.kit === kitId);

    for (const file of files) {
      const base = file.slice(0, -4);
      const rule = rules.find((r) => r.match.test(base));
      if (!rule) continue;
      if (ONLY && !ONLY.test(base)) continue;

      for (let r = 0; r < rule.rots; r++) {
        // Namespaced by kit: `barrel`, `grass`, `structure` and `rock_largeA`
        // all exist in more than one kit, and an unqualified name silently
        // lets whichever kit is enumerated first win.
        const id = kitId + '/' + base + (rule.rots === 1 ? '' : '#' + r);
        if (seen.has(id)) continue;
        seen.add(id);
        jobs.push({
          id,
          group: rule.group,
          kit: kitId,
          yaw: (r / rule.rots) * Math.PI * 2,
          remapLeaves: LEAF_KITS.has(kitId),
          url: '/' + ['assets-src', 'raw', kit.dir, kit.glb, file]
            .map(encodeURIComponent).join('/').replaceAll('%2F', '/'),
        });
      }
    }
  }
  return jobs;
}

/** The generated manifest module. Typed, so a missing sprite is a build error. */
function manifestSource(sprites, pages, pageSize, density) {
  const ids = Object.keys(sprites).sort();
  const groups = {};
  for (const id of ids) (groups[sprites[id].group] ??= []).push(id);

  const rows = ids.map((id) => {
    const s = sprites[id];
    return `  ${JSON.stringify(id)}: { p: ${s.page}, x: ${s.x}, y: ${s.y}, w: ${s.w}, h: ${s.h}, ax: ${s.ax}, ay: ${s.ay} },`;
  }).join('\n');

  const groupRows = Object.keys(groups).sort().map(
    (g) => `  ${JSON.stringify(g)}: [\n${groups[g].map((id) => `    ${JSON.stringify(id)},`).join('\n')}\n  ],`,
  ).join('\n');

  return `/* eslint-disable */
/**
 * GENERATED by packages/tools/src/bake/bake.mjs - do not edit.
 *
 * Baked from CC0 Kenney model kits at the game's own isometric projection,
 * so \`ax\`/\`ay\` is the pixel inside the sprite that sits on the grid cell.
 * Re-run the baker to change anything here.
 */

export interface AtlasFrame {
  /** Atlas page index. */
  p: number;
  x: number;
  y: number;
  w: number;
  h: number;
  /** Anchor: the model origin, in sprite pixels from the top left. */
  ax: number;
  ay: number;
}

export const ATLAS_PAGE_SIZE = ${pageSize};

/**
 * Sprites are baked this many times larger than they are drawn, so they stay
 * sharp when the camera zooms in. Divide sprite width, height and anchor by
 * it to get world pixels.
 */
export const ATLAS_DENSITY = ${density};
export const ATLAS_PAGES: readonly string[] = [
${pages.map((f) => `  ${JSON.stringify('/atlas/' + f)},`).join('\n')}
];

export const ATLAS: Record<string, AtlasFrame> = {
${rows}
};

/** Sprite ids by catalogue group, for "give me any tree" style picks. */
export const ATLAS_GROUPS: Record<string, readonly string[]> = {
${groupRows}
};

export type AtlasGroup = keyof typeof ATLAS_GROUPS;
`;
}

async function main() {
  const jobs = await planJobs();
  if (jobs.length === 0) throw new Error('nothing to bake - is assets-src/raw populated?');
  console.log(`baking ${jobs.length} sprites from ${new Set(jobs.map((j) => j.kit)).size} kits`);

  const { server, port } = await serve();
  const browser = await chromium.launch({
    args: [
      '--use-gl=angle',
      '--use-angle=swiftshader',
      '--enable-unsafe-swiftshader',
      '--disable-gpu-sandbox',
    ],
  });
  const page = await browser.newPage();
  const failures = [];
  page.on('pageerror', (e) => failures.push('page error: ' + e.message));

  await page.goto(`http://127.0.0.1:${port}/packages/tools/src/bake/page/index.html`);
  await page.waitForFunction(() => window.bakeReady === true, null, { timeout: 60_000 });

  let done = 0;
  for (const job of jobs) {
    try {
      await page.evaluate(
        ([url, id, yaw, group, kit, leaves]) => window.bake.one(url, id, yaw, group, kit, leaves),
        [job.url, job.id, job.yaw, job.group, job.kit, job.remapLeaves],
      );
    } catch (err) {
      failures.push(`${job.id}: ${String(err).split('\n')[0]}`);
    }
    if (++done % 40 === 0 || done === jobs.length) {
      console.log(`  ${done}/${jobs.length}`);
    }
  }

  const result = await page.evaluate((size) => window.bake.finish(size), PAGE_SIZE);
  await browser.close();
  server.close();

  await mkdir(OUT_IMG, { recursive: true });
  const files = [];
  for (let i = 0; i < result.images.length; i++) {
    const name = `props-${i}.png`;
    const b64 = result.images[i].slice(result.images[i].indexOf(',') + 1);
    await writeFile(join(OUT_IMG, name), Buffer.from(b64, 'base64'));
    files.push(name);
  }
  await writeFile(OUT_MANIFEST, manifestSource(result.sprites, files, PAGE_SIZE, result.density));

  const count = Object.keys(result.sprites).length;
  console.log(`\nwrote ${files.length} atlas page(s), ${count} sprites`);
  console.log('  images   ' + OUT_IMG);
  console.log('  manifest ' + OUT_MANIFEST);
  if (failures.length) {
    console.log(`\n${failures.length} failed:`);
    for (const f of failures.slice(0, 20)) console.log('  ' + f);
  }
}

await main();
